// GENERATED by tools/build-zalo-read-core.cjs; edit the source service, never this file.
var THU_TUAN_TZ = 'Asia/Ho_Chi_Minh';
var THU_TUAN_TEST_RECIPIENT_ID_ = 'THU_TUAN_TEST_OVERRIDE';
var THU_TUAN_NOTEBOOK_NOTE = 'NotebookLM chỉ là công cụ tra cứu thêm, không phải nguồn chính thức. Hãy đối chiếu nội dung với nguồn gốc trích dẫn.';
// Sheet schema retains legacy columns for backward-compatible imports.
var THU_TUAN_HEADERS = {
  LoiDay_NoiDung: ['Ky','MaLoiDay','NoiDungNguyenVan','NguonTrich','GoiYLienHe','TrangThai','NguoiDuyet','NgayDuyet','PhienBan','DauVanBanDuyet',
    'ChuDe','BoiCanh','PhanTich','LienHeCAND','LienHeAnNinhDoiNgoai','HanhDongTuanNay','NotebookLM_URL'],
  ThuTuan_NguoiNhan: ['MaCB','Email','TrangThai','NgayDangKy'],
  ThuTuan_NhatKyGui: ['Khoa','Ky','MaCB','MaLoiDay','PhienBan','DauVanBanDuyet','TrangThai','CapNhatLuc','MaLoi'],
  ThuTuan_Zalo_NhatKyGui: ['Khoa','Ky','MaCB','MaLoiDay','PhienBan','DauVanBanDuyet','TrangThai','CapNhatLuc','MaLoi',
    'Transport','Environment','TargetHash','Part','PartCount','PlanHash','MessageId']
};

function thuTuanWeekKey_(date) {
  var local = Utilities.formatDate(date, THU_TUAN_TZ, 'yyyy-MM-dd');
  var day = new Date(local + 'T00:00:00Z');
  day.setUTCDate(day.getUTCDate() - ((day.getUTCDay() + 6) % 7));
  return day.toISOString().slice(0,10);
}

function thuTuanText_(value) { return value == null ? '' : String(value).trim(); }
function thuTuanIsDate_(value) { return Object.prototype.toString.call(value) === '[object Date]'; }
// LEGACY INPUT ONLY — DO NOT RENDER. Never add these fields to the canonical payload.
var THU_TUAN_LEGACY_INPUT_FIELDS_ = ['GoiYLienHe','LienHeAnNinhDoiNgoai'];
var THU_TUAN_CANONICAL_VERSION_ = 2;
var THU_TUAN_CANONICAL_FIELDS_ = ['Ky','ChuDe','MaLoiDay','NoiDungNguyenVan','NguonTrich','BoiCanh','PhanTich',
  'LienHeCAND','HanhDongTuanNay','NotebookLM_URL','TrangThai','NguoiDuyet','NgayDuyet','PhienBan'];
function thuTuanCanonicalContent_(content) {
  var canonical = {};
  THU_TUAN_CANONICAL_FIELDS_.forEach(function(key) { canonical[key] = content && content[key] != null ? content[key] : ''; });
  canonical.DauVanBanDuyet = content && content.DauVanBanDuyet != null ? content.DauVanBanDuyet : '';
  return canonical;
}
/** Versioned approval stamp over canonical fields only; the key lives only in Script Properties. */
function thuTuanDigest_(content, secret) {
  if (typeof secret !== 'string' || secret.length < 32) throw new Error('MISSING_APPROVAL_SECRET');
  var canonical = thuTuanCanonicalContent_(content);
  var value = [THU_TUAN_CANONICAL_VERSION_].concat(THU_TUAN_CANONICAL_FIELDS_.map(function(key) {
    var raw = canonical[key];
    if (key === 'NgayDuyet') {
      if (raw == null || raw === '') return '';
      var date = new Date(raw);
      // Second precision: Sheets may not round-trip milliseconds.
      return Number.isFinite(date.getTime()) ? new Date(Math.floor(date.getTime() / 1000) * 1000).toISOString() : 'INVALID:' + String(raw);
    }
    return raw == null ? '' : String(raw);
  }));
  return Utilities.computeHmacSha256Signature(JSON.stringify(value), secret, Utilities.Charset.UTF_8)
    .map(function(b) { return ('0' + ((b + 256) % 256).toString(16)).slice(-2); }).join('');
}

function thuTuanNotebookUrl_(value) {
  var url = thuTuanText_(value);
  return /^https:\/\/notebooklm\.google\.com\/notebook\/[A-Za-z0-9_-]+\/?(?:[?#][^\s<>"']*)?$/i.test(url) ? url : '';
}
/** NotebookLM is optional; a non-empty value must be a valid NotebookLM notebook link. */
function thuTuanNotebookOk_(value) { return !thuTuanText_(value) || !!thuTuanNotebookUrl_(value); }

var THU_TUAN_REQUIRED = ['ChuDe','MaLoiDay','NoiDungNguyenVan','NguonTrich','BoiCanh','PhanTich',
  'LienHeCAND','HanhDongTuanNay','PhienBan'];

/** '' when approved, complete, reviewer allow-listed and stamp matches; otherwise a reason code. */
function thuTuanApprovalProblem_(row, digest, approvers) {
  if (!row || row.TrangThai !== 'DaDuyet') return 'NOT_APPROVED';
  var reviewer = thuTuanText_(row.NguoiDuyet).toLowerCase();
  if (!reviewer) return 'MISSING_REVIEWER';
  if (!approvers || approvers.indexOf(reviewer) < 0) return 'REVIEWER_NOT_ALLOWED';
  if (!row.NgayDuyet || !Number.isFinite(new Date(row.NgayDuyet).getTime())) return 'INVALID_APPROVAL_DATE';
  if (THU_TUAN_REQUIRED.some(function(field) { return !thuTuanText_(row[field]); })) return 'INCOMPLETE_CONTENT';
  if (!thuTuanNotebookOk_(row.NotebookLM_URL)) return 'INVALID_NOTEBOOKLM_URL';
  if (typeof digest !== 'string' || !digest || row.DauVanBanDuyet !== digest) return 'STAMP_MISMATCH';
  return '';
}

function thuTuanSheet_(id, name) {
  if (!id) throw new Error('MISSING_SHEET_CONFIG');
  var sheet = SpreadsheetApp.openById(id).getSheetByName(name);
  if (!sheet) throw new Error('MISSING_SHEET');
  var expected = THU_TUAN_HEADERS[name];
  if (sheet.getLastColumn() !== expected.length) throw new Error('INVALID_HEADERS');
  var actual = sheet.getRange(1,1,1,expected.length).getValues()[0];
  if (actual.length !== expected.length || expected.some(function(h,i) { return actual[i] !== h; })) throw new Error('INVALID_HEADERS');
  return sheet;
}

function thuTuanRows_(sheet, name) {
  if (sheet.getLastRow() < 2) return [];
  var headers = THU_TUAN_HEADERS[name];
  return sheet.getRange(2,1,sheet.getLastRow()-1,headers.length).getValues().map(function(row,i) {
    var item = { _row: i+2 };
    headers.forEach(function(h,j) { item[h] = row[j]; });
    return item;
  }).filter(function(row) { return headers.some(function(h) { return thuTuanText_(row[h]); }); });
}

function thuTuanForKey_(rows, key) { return rows.filter(function(row) { return thuTuanText_(row.Ky) === key; }); }

function thuTuanZaloGraphemes_(text) {
  if (typeof Intl !== 'undefined' && typeof Intl.Segmenter === 'function')
    return Array.from(new Intl.Segmenter('vi', { granularity:'grapheme' }).segment(text), function(x) { return x.segment; });
  var units = Array.from(text), clusters = [], regionalCount = 0;
  units.forEach(function(ch, i) {
    var cp = ch.codePointAt(0), prev = units[i-1];
    if (cp >= 0xD800 && cp <= 0xDFFF) throw new Error('ZALO_INVALID_UNICODE');
    var regional = cp >= 0x1F1E6 && cp <= 0x1F1FF;
    var continuation = /\p{M}/u.test(ch) || cp === 0x200D || prev === '\u200D' ||
      (cp >= 0xFE00 && cp <= 0xFE0F) || (cp >= 0xE0100 && cp <= 0xE01EF) ||
      (cp >= 0x1F3FB && cp <= 0x1F3FF) || (cp >= 0xE0020 && cp <= 0xE007F) ||
      (ch === '\n' && prev === '\r') || (regional && regionalCount % 2 === 1);
    if (continuation && clusters.length) clusters[clusters.length-1] += ch;
    else clusters.push(ch);
    regionalCount = regional ? regionalCount+1 : 0;
  });
  return clusters;
}

function thuTuanZaloSplit_(text) {
  if (typeof text !== 'string' || !text || /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/u.test(text))
    throw new Error('ZALO_INVALID_UNICODE');
  var clusters = thuTuanZaloGraphemes_(text), parts = [], part = '';
  clusters.forEach(function(cluster) {
    if (cluster.length > 1800) throw new Error('ZALO_TEXT_TOO_LONG');
    if (part.length + cluster.length > 1800) { parts.push(part); part = ''; }
    part += cluster;
  });
  if (part) parts.push(part);
  if (parts.length > 3) throw new Error('ZALO_TEXT_TOO_LONG');
  return parts;
}
